### ISSUE TITLE
Responsiveness not working properly in public page

### ISSUE THREAD

**Issue by niinortey** [wiregh/wevotegh#2]
When the screen size changes for the the public/welcome page, the page becomes terribly ugly, pluss the get started and register buttons are missing.
Same issue with you view the page on mobile web browser. 
The page needs to be consistent both in normal desktop view and mobile browser view.
![image](https://cloud.githubusercontent.com/assets/2520579/24068805/03df15f6-0b90-11e7-9b44-d8e36b8b77b5.png)

**Comment by i-am-gazali** [comment]
working on it

On Mar 18, 2017 4:05 AM, "Enoch jr. Nii Nortey Wilson" <
notifications@github.com> wrote:

When the screen size changes for the the public/welcome page, the page
becomes terribly ugly, pluss the get started and register buttons are
missing.
Same issue with you view the page on mobile web browser.
The page needs to be consistent both in normal desktop view and mobile
browser view.
[image: image]
<https://cloud.githubusercontent.com/assets/2520579/24068805/03df15f6-0b90-11e7-9b44-d8e36b8b77b5.png>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/wiregh/wevotegh/issues/2>, or mute the thread

**Comment by niinortey** [comment]
I have made some changes to the login page. you will need to do a pull.
As per my mail we need to work on one code base for all pages. The login pages are not merged into one.
Have a loot at the login.html file and notice how I uded 
```
[ngClass]="(viewMode.isBrowser) ? 'browser' : 'app'"
```
 in there... you can see the two selectors .browser and .app inside the login.scss.
This results in the same login page being presented differently when running as an app on a device and when running in a desktop webbrowser or mobile web browser.
